### ISSUE TITLE
Getting an ImportError on follow_orders strategy

### ISSUE THREAD

**Issue by pnomolos** [ihaywood3/DEXBot#6]
I'm trying to use the follow_orders strategy but am getting the following error:

```
  File "/home/---/.local/lib/python3.5/site-packages/dexbot-0.1.13-py3.5.egg/dexbot/strategies/follow_orders.py", line 6, in <module>
    from dexbot.basestrategy import BaseStrategy, ConfigElement
ImportError: cannot import name 'ConfigElement'
```

**Comment by ihaywood3** [comment]
dexbot/basestrategy.py should define ConfigElement
Are you trying to use follow_orders with the Codaone version of DEXBot?
Unfortunately the two codebases are not fully compatible. 
I'm in touch with the Codaone devs and hope to rectify this eventually.

**Comment by pnomolos** [comment]
Oh, I see what's going on.  The Codaone version produces dexbot-cli and dexbot-gui but this one still builds just dexbot, so I was calling the wrong one :)
